Backport index.d.ts from 3.x branch
This fixes

```
error TS2345: Argument of type ... is not assignable to parameter of type .. Property 'functional' is missing in type ..
```

For vue 2